Ejercicio9Api/Mengassini.EF/Mengassini.MVC/Models/ProductView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mengassini.MVC.Models
{
    public class ProductView
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public decimal Precio { get; set; }
    }
}

Ejercicio9Api/Mengassini.EF/Mengassini.MVC/Models/RegionView.cs
namespace Mengassini.MVC.Models
{
    public class RegionView
    {
        public int Id { get; set; }

        public string Description { get; set; }
    }
}

Ejercicio9Api/Mengassini.EF/Mengassini.MVC/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mengassini.MVC.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error
        public ActionResult Index()
        {
            return View();
        }
    }
}

Ejercicio9Api/Mengassini.EF/Mengassini.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mengassini.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Mengassini Alan.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "";

            return View();
        }
    }
}

Ejercicio9Api/Mengassini.EF/Mengassini.MVC/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mengassini.EF.Logic;
using Mengassini.EF.Entities;
using Mengassini.MVC.Models;

namespace Mengassini.MVC.Controllers
{
    public class ProductController : Controller
    {
         ProductsLogic logic = new ProductsLogic();
        // GET: Product
        public ActionResult Index()
        {
            List<Products> productos = logic.GetAll();

            /*List<ProductView> productsView = productos.Select(p => new ProductView
            {
                Id = p.ProductID,
                Nombre = p.ProductName,
                Precio = (decimal)p.UnitPrice
            }).ToList();*/

            return View(productos);
        }

        public ActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Insert(ProductView productView)
        {
            try
            {
                Products productEntity = new Products
                {
                    ProductName = productView.Nombre,
                    UnitPrice = productView.Precio
                };
                logic.Add(productEntity);
                return RedirectToAction("index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Error");
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                logic.Delete(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Error");
            }
        }
    }
}

Ejercicio9Api/Mengassini.EF/Mengassini.MVC/Controllers/RegionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mengassini.EF.Logic;
using Mengassini.EF.Entities;
using Mengassini.MVC.Models;

namespace Mengassini.MVC.Controllers
{
    public class RegionController : Controller
    {
        RegionLogic logic = new RegionLogic();
        // GET: Region
        public ActionResult Index()
        {
            try
            {
                List<Region> regiones = logic.GetAll();
                List<RegionView> regionViews = regiones.Select(s => new RegionView
                {
                    Id = s.RegionID,
                    Description = s.RegionDescription
                }).ToList();
                return View(regionViews);
            }
            catch(Exception ex)
            {
                return RedirectToAction("Index", "Error");
            }
        }

        public ActionResult Update(int id)
        {
            List<Region> region = logic.GetAll();
            List<RegionView> regionsView = region.Where(r => r.RegionID == id).Select(r => new RegionView
            {
                Id = r.RegionID,
                Description = r.RegionDescription
            }).ToList();
            RegionView regionView = regionsView[0];
            return View("Insert", regionsView);
        }

        public ActionResult Insert()
        {
            return View("InsertEdit", new RegionView());
        }

        public ActionResult Edit(int id)
        {
            List<Region> region = logic.GetAll();

            List<RegionView> regionsView = region.Where(r => r.RegionID == id).Select(r => new RegionView
            {
                Id = r.RegionID,
                Description = r.RegionDescription
            }).ToList();

            RegionView regionView = regionsView[0];

            return View("InsertEdit", regionView);
        }


        [HttpPost]
        public ActionResult InsertUpdate(RegionView regionsView)
        {
            if(regionsView.Id <= 0)
            {
                try
                {
                    Region regionEntity = new Region
                    {
                        RegionDescription = regionsView.Description
                    };
                    logic.Add(regionEntity);
                    return RedirectToAction("index");
                }
                catch (Exception ex)
                {
                    return RedirectToAction("Index", "Error");
                }
            }
            else
            {
                try
                {
                    Region regionEntity = new Region
                    {
                        RegionDescription = regionsView.Description
                    };
                    logic.Update(regionEntity);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    return RedirectToAction("Index", "Error");
                }
            }                                                                                 
        }


        public ActionResult Delete(int id)
        {
            try
            {
                logic.Delete(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Error");
            }
        }
    }
}

Ejercicio9Api/Mengassini.EF/Mengassini.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Ejercicio9Api/Mengassini.EF/Mengassini.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Ejercicio9Api/Mengassini.EF/Mengassini.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Ejercicio9Api/Mengassini.EF/Mengassini.MVC/Views/Product/Index.cshtml
@model List<Mengassini.EF.Entities.Products>

@{
    ViewBag.Title = "Products Page";
}

<h1>Index de Products</h1>

<table class="table">
    <thead>
        <tr>
            <td scope="col">ID</td>
            <td scope="col">Nombre Producto</td>
            <td scope="col">Precio Producto</td>
            <td scope="col">Action</td>
            <td scope="col">Action</td>

        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model)
        {
        <tr>
            <td scope="row">@product.ProductID</td>
            <td>@product.ProductName</td>
            <td>@product.UnitPrice</td>
            <td>@Html.ActionLink("Update", "Update", new { id = product.ProductID })</td>
            <td>@Html.ActionLink("Borrar", "Delete", new { id = product.ProductID }, new { onclick = "return confirm('Estas seguro que deseas borrar?')" })</td>
        </tr>
        }
    </tbody>
</table>

<div>
    @Html.ActionLink("Insertar Nuevo Producto", "Insert")
</div>

Ejercicio9Api/Mengassini.EF/Mengassini.MVC/Views/Product/Insert.cshtml
@model Mengassini.MVC.Models.ProductView
@{
    ViewBag.Title = "Product Page";
}

<h1>Vista para insertar</h1>

@using (Html.BeginForm("Insert", "Product", FormMethod.Post))
{
    <label>Nombre: </label> @Html.TextBoxFor(p => p.Nombre)
    <label>Precio: </label> @Html.TextBoxFor(p => p.Precio)
    <input type="submit" class="btn btn-success" value="Guardar" />
}

Ejercicio9Api/Mengassini.EF/Mengassini.MVC/Views/Region/Insert.cshtml
@model Mengassini.MVC.Models.RegionView
@{
    ViewBag.Title = "Region Page";
}

<h1>Vista para insertar</h1>

@using (Html.BeginForm("InsertUpdate","Region",FormMethod.Post))
{
    <label>Description: </label> @Html.TextBoxFor(r => r.Description)
    <input type="submit" class="btn btn-success" value="Guardar" />
}

Ejercicio9Api/Mengassini.EF/Mengassini.MVC/Views/Region/index.cshtml
@model List<Mengassini.MVC.Models.RegionView>


@{
    ViewBag.Title = "Region Page";
}

<h1>Index de Region</h1>

<table class="table">
    <thead>
        <tr>
            <td scope="col">ID</td>
            <td scope="col">Description</td>
            <td scope="col">Action</td>
            <td scope="col">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var region in Model)
        {
        <tr>
            <th scope="row">@region.Id</th>
            <td>@region.Description</td>
            <td>@Html.ActionLink("Update", "Update", new { id = region.Id })</td>
            <td>@Html.ActionLink("Borrar", "Delete", new { id = region.Id }, new { onclick = "return confirm('Estas seguro que deseas borrar?')" })</td>
        </tr>
        }
    </tbody>
</table>

<div>
    @Html.ActionLink("Insertar Nueva Region", "Insert")
</div>

Ejercicio9Api/Mengassini.EF/Mengassini.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Mengassini-App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Region", "index", "Region")</li>
                    <li>@Html.ActionLink("Producto", "index", "Product")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>